meta_product_name: "Annie Puygrenier"
meta_title: "Annie Puygrenier | Web and Mobile Developer Full-Stack"
meta_description: "Web and Mobile Developer Full-Stack with a passion for building beautiful and functional application."
meta_image: "ME.jpg" # should exist in `app/assets/images/`